server:
  port: 8090
  undertow:
    accesslog:
      enabled: true
      dir: /data/logs/


eureka:
  #EurekaInstanceConfigBean
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.hostname}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://192.168.51.218:1111/eureka/

spring:
  dataSource:
    driverClassName: com.mysql.jdbc.Driver
    writeConfig:
      url: jdbc:mysql://127.0.0.1:3306/xiaowo_goods?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
    readConfig:
      url: jdbc:mysql://127.0.0.1:3306/xiaowo_goods?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456

mybatis:
    # 批量插入或更新时，每次事务执行的插入或更新数据行数  
  writeMapperLocations: classpath:mapper/write/**.xml
  readMapperLocations: classpath:mapper/read/**.xml
  config: mybatis-config.xml
  rows_per_transaction: 500

logging:
  level:
    #root: INFO
    com.xiaowo: DEBUG

